token:
  expiration_time: 86400000
  secret: '{cipher}AQC6oV3u0ZYfPXDlsuYcxJABTTX5NHrFmwyoAkr9fRtXM2nj6ndD0GoQpy11lHcy58Bk1/rFKTSQFghzZd4lnxLUgKWkmT+a3Hkiv+pq/jrxncz/8FrUBQNDTtKrlNFkyQvJRBn5azFVxtGITvSmVTY9P+wAwnqjyyyA8Wlkn62e+vwQXTlaxoEGtY4ry1aXgHB7hBXET8Uq4rFP5ECuNNMJpWQbx5KwrxeA9SdTAVECvR/OUOwxTn+ShcU/M/+oT26D9rT589jcnKc32Pw6YQV1bX/QH/tyn2ti84PyAomXZaUAq6DZqz1OWcUu2msvtzhrq35etX3ZIHnzuMF6LlYSeM1rxzFsj9T3CyJfMFnClMaBk5zA5cvV9dRU/4JRJLo='

gateway:
  ip: 192.168.0.8

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQApmZXwycycXdKwq6d1TqXCHrJhlyAL1X0Yj9ueJT8vAPpw8T2uk1vKy94Llzuq8dZsK5L/qqh2TcXRvTnDTjKJabHjnWjE47DHaB4E/xESMa59MObVCJo/hQg6XIciCfZ2o7Rs66RURx7+aDXpEceH7bJt4qZzPurRk/Xx1vVd9aEXfU8A7Wsib9xSv8mzDw9AXPUe8CVjkTF34kbsWmVSVGAAharntyNo2C22BJv6sgfsjfzEMUtzfb7TN9mnp0JLTbdgmReyT+94eZ8Lz38kpMeTeTbZytzR2Ww1VcB9L4KwTigpUIs5gxWdkNbMCZNqW8455C6LXQIuIiT67cWCHaMwGCaqe6GR+rVcP+9rUv3qD0P1rNoLg80EjIjLGKo='
    
order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: orders is empty
